# Run `travis lint` when changing this file to avoid breaking the build.
# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_51
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r opentracing-contrib/java-activespan BINTRAY_USER=your_github_account
  - secure: "kUlDX2huODNAWdoTjOOzsthNsDxIU4DcNIXmdaXKAiOrASDHRldS6PLoZlEW55UEqsnEveOrWlm9DU9xEeznf8Rt3GU7PvCm8+LMRyWmkXbHhiF0dYA9yxSIpM9TeXhlqx0eYO3oNQ6U8YmIupOtfEHn39mkU7WZIwUqOKjKQCT9MNeBXPfzQPkXseCHtxBH4Axe6qng07eDWTY/k1IxGaL9F/k27371qlnS/xFLp6pSPQ990jrKX1xY5Mw68PFrqWJRwMiC0opotNzM69G+5av4yMwPakf4Sf0hZjm2+9voWmChecFVbG81NJK9caWfFH/BQqVLsvns28VIYfaM7bk2/LzpWg7/1XABPDfjulBU80vUOHvHXDaEj0VFng7NEO248OvbRfJRbtDv5+LheOjBiiJHCFIfH1hy4j1NCzLlI0yCS8/cycIvXI1VTqVFUGErL8wS7Sv5zh/E+97qTg08k+pLJTE4z/n5+Ehfsfp94snRwIQSrfRh/ccT97f7qNjlRfflYt2bFpMjNLXRpcrm34Y990c64Usr0ONdFN/hT2i5+K+kwshH4pYrnX9KzHVweVFAQt7bhyFPJjNrdKSOG2RgFDwRyAtcgNKx9oz5F4S7oe4dkd9SoSC0KB/nQxsBy+KBm1O4Camq7u2OgnByn1FIbavCxWHxGhOkOeE="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "HG1jFM22Tfj1LEhLEcMC5Y9xFajsqfRYYy2GRv3ZmDBP+7lxfevJEjoPE+xxBvUyZuouNKVfSLLduVm8JLhK4xOJUqI+H1xivntQH7fRU9u14XX8L2U5UJHNEp+yRx/nXzuTMUJqNZ75FSUBkVTRIQwAAi8PtIrtHef/jEgUUoZfR9vd3WbB85VWXoKxGr1yHa4sh9RDFKDG3JhnSTdbGhtX3mglTVdOP3rqjBszKsYlzDJjStwGuPZU7F3a1OcUZ86F3HQdIgr9QTE+JWVIF9AGq3GMA/1cBtdjAvYFpkZUmtMwMUZib2uykvLfwHxiQJqVlebB68EZSs+PRnPmOeNrkVx3USGFEUSHtTaoimeMG124nlHABhexgmBR6V+mksfXKESxiVuFn50kWGBKZAJUQ6CaNJQl8Qexl7BdVReJu2Gq6yHt6lcc1DotOgvpPAGic+uMqa8IRCaBUhPx2iuws2Q4Kx/3/qOOrIwiIysEq/CtIhNwjhSNQf/hkFX37IqXZ8EWyY771qCrCbwqvBVShO7Qywy4FMHAWRsfmTQYzHfo6STGKv1Yzit5ny2K/do+SgAhYhoT9L07B+/BzfHvB1VJ3Qv63PwQ9ANiyHyAIAR/SMagpb7CMNr1f1atEyCBiIRIZY7t/375/U9WvNVupj7eWYGw1Ocjfculywo="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "X3b+6lVeFlHrZISNaVqyCZq04JQPmY0xv9+QQdzG5rRqWJdLUAV5kT7cNHccJ8gy83c5Zs72u/jwugIpqiQNHHzEkbF77CUwlb365LuatcHHR/KxVoO264rJLorW5UuSebzlZ0feUegaN7t5QQeEyp7bVWg9M6rNjBVocgvi4EFATDBTFxodri9Ktqr0EbTU89BXgxYdbanBwrNu78DDQFIlookYFOwe/8N9qPgjHvmLjt5BtOGNwWIhAmvjqPHdgkq6v/iyqhcjX19wcRGmS+Xk8sFFjeH68DTrNmA6lAuiDvMD8MhFuPeI6gM9X6cHMtubFccxiG6gsBbiN2T43kelSu6DgTilMWWg/BWKJI82ZhRPX2mT1YtQYlYm0VQ/GnrPyKs7pVzEzCXDg/feUa1DnBsu9x/oTt+MeaLUhY2PfDuSJthpUMLr+B9kOt+e1kXvUK1PR/ukYxveXgvA8eQpSW49Tm2/BXdl0Ig2ZBCD9INQO/ynpql6a5xcXpoiRyg1eq/g42vvJyC1/2pl0fS2YT4s1jkknTVaQJ0FUhzIdqCpnnBmpXVk+n6DGZraio9dfkHdJx6I4Y+FmO1o+R18X316uwdmPK3aQ0Hxwa7/0scNBokbdXxvGxLbdpUBIiicxsQN/RSikFD3mTIgeAPyabCe7Zulmvgufw35txk="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "YpUSzZYRhzCCAxNQap9Jx8dK/9N7Br5zejEA7Gdi3iO2HLwFp6zX+xLTand6tSGOy6/gYMo9won7BKvPI26hkVRLPwRtG/W9YbONkngO2zR0s+Ug2e0dUr3UcvxVOQ1Xrj2vozTzxXTwGQpwBkCgKDAD3iQAZSHgnsBAbw3+BSX/1egXbIaWjiC0cO75ubwQcERaVFSKaWPGUiUf/6KyO0wtIPIeX7wWn/JUllbCOEEEhW1BSgWbLZP1w0LEvKpoFrfBq6fVrr4TT64sOWoebMWxZx63Z6SPPf5uOx7wNS1XA4plo1C/XGsBKeWTqLlH/AebE83clGBCU3LJNDO1K6J9rWqr2GxcclURalVDBQph6pDmra1s36jL9yPKb0Fg+W9Bvb9YtwTqRNji5ZuD7nlX5u2UTZQQ0MToTI9c2jomMCWMeBVdqBZVm6v2Giwrja/PlObwgaSY6fzTS+mlsx3EIHqdaimGVZb26Z4jsj9zZS49Y8r1EufijlDsfaNvslpUiojPz4nF9x73vmnl1HqBuXhs7FrDOWj+PSw/qYgIeSeTNbu5b0FK/EWVnjHzUvJ1UDyQRSSTU0rcYfVhE3gJMEbRRB/eDdYa7H2pr/uoZ4+VdeddLhhepwTZJ1PRuuNn55s1Y1PQl3EyayoHD1ABKyiiRc/GGS2fY6fqZl0="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "jB2bn9K8z1DAbqHorduIGytoJVrKxqoAV9bdC57xtUmdbHYUwsCqnnvcOfUAiMhCDtSQl700jqSP1CuZF6mdO7Fva5e4FUF4ITGLScQkC1QQCVebbRKo6kBpdCqeEEWB9lfAqXFEgTORBUMzTOgsMJWGSnvwhDxRn3eqNkk0kZWYh4BT/odh6qV4jpolvMQQ6zXVRXsMCAehqPI6LEmp6ln7Bi9VFkoFyXiqCl3bQ9c2fT4YxdYKRf1X8lJ+fcq/FU939FDvDX2lJqFWDLUXYtRcADxdIh5ZZN15BcDj39MekNAk4M/1j4lPJJUHCUhzpeVP0dP5Av5eDWEEEyZpkpWtqgfshWFApckf6Sa4JRqOIqn8YaemF9dvhc2CSBXC8E28GejmsrzFPv5HsP07581VN8lIN9Us9WDiNUqz0h6aZciVr/AzBSgVS0kLj54eo6e+860TrX3b2L25IlnehfO6+W5205OBYfeLnL46NK76pGzZ0Oz18wxkT14HBykaIgRnXmZowWzHIEwAo1xJHIBmqrrUkLMhRn4bu1BSiEbTC5yD94YYgj1IXGAwuMaH2EgmPgJymecwhjjrC0TlEgLYTS8VOQrm5Ap77FZopnXJYYPjTxP99/sVBJKUCBPlpPCQXrxkrXeFeDUTY0dK9wQX07EousAcrBynNQVSuuc="
